### ISSUE TITLE
Make Recipes Collection

### ISSUE THREAD

**Issue by clyyoung** [taste-technologists/taste-technologists#19]
Please do work for this task in a branch named issue-019.

- Recipes collection should have name, picture, time, description, ingredients, instructions, tags

**Comment by mendechris** [comment]
The collection should be usable right now.
We'll want to create links to go to the individual recipe pages eventually. 

The schema for the collection includes:

1. name
2. picture
3. time
4. description
5. servings
6. tags
7. ingredients
8. instructions
9. owner (for later editing capabilities)
